import { NgxUiLoaderConfig } from "ngx-ui-loader";
import { AngularEditorConfig } from '@kolkov/angular-editor';

export enum IActionType {
    ADD="ADD",
    EDIT="EDIT"
}


export const nationality = [
{id:2,name:"Bahraini"},
{id:6,name:"Kuwaiti"},
{id:10,name:"Omani"},
{id:13,name:"Qatari"},
{id:14,name:"Saudi Arabian"},
{id:17,name:"Emirati (UAE)"},
{id:80,name:"Indian"},
{id:18,name:"Afghan"},
{id:19,name:"Albanian"},
{id:1,name:"Algerian"},
{id:157,name:"American (US)"},
{id:172,name:"Andorran"},
{id:21,name:"Angolian"},
{id:22,name:"Argentine"},
{id:23,name:"Armenian"},
{id:24,name:"Australian"},
{id:25,name:"Austrian"},
{id:26,name:"Azerbaijani"},
{id:27,name:"Bahamese"},
{id:28,name:"Bangladeshi"},
{id:29,name:"Barbadian"},
{id:30,name:"Belarusian"},
{id:31,name:"Belgian"},
{id:32,name:"Belizian"},
{id:33,name:"Beninese"},
{id:34,name:"Bosnian"},
{id:36,name:"Brazilian"},
{id:156,name:"British (UK)"},
{id:37,name:"Bruneian"},
{id:38,name:"Bulgarian"},
{id:39,name:"Burkinabe"},
{id:111,name:"Burman"},
{id:40,name:"Burundian"},
{id:41,name:"Cameroonian"},
{id:42,name:"Canadian"},
{id:43,name:"Cayman"},
{id:44,name:"Central African National"},
{id:45,name:"Chadian"},
{id:46,name:"Chilean"},
{id:47,name:"Chinese"},
{id:48,name:"Colombian"},
{id:49,name:"Comorian"},
{id:50,name:"Congolese"},
{id:51,name:"Costa Rican"},
{id:52,name:"Croat"},
{id:53,name:"Cuban"},
{id:54,name:"Cypriot"},
{id:55,name:"Czech"},
{id:56,name:"Danish"},
{id:57,name:"Djiboutian"},
{id:58,name:"Dominican"},
{id:114,name:"Dutch"},
{id:115,name:"Dutch (Netherlands Antilles)" },
{id:60,name:"Ecuadorian"},
{id:3,name:"Egyptian"},
{id:62,name:"Eritrean"},
{id:63,name:"Estonian"},
{id:64,name:"Ethiopian"},
{id:65,name:"Fijian"},
{id:124,name:"Filipino"},
{id:66,name:"Finnish"},
{id:67,name:"French"},
{id:68,name:"Gabonese"},
{id:69,name:"Gambian"},
{id:70,name:"Georgian"},
{id:71,name:"German"},
{id:72,name:"Ghanaian"},
{id:73,name:"Greek"},
{id:74,name:"Guatemalan"},
{id:75,name:"Guyanese"},
{id:76,name:"Haitian"},
{id:77,name:"Honduran"},
{id:78,name:"Hungarian"},
{id:79,name:"Icelandic"},
{id:81,name:"Indonesian"},
{id:82,name:"Iranian"},
{id:4,name:"Iraqi"},
{id:83,name:"Irish"},
{id:84,name:"Italian"},
{id:85,name:"Ivorian"},
{id:86,name:"Jamaican"},
{id:87,name:"Japanese"},
{id:5,name:"Jordanian"},
{id:88,name:"Kazakh"},
{id:89,name:"Kenyan"},
{id:90,name:"Korean (North)"},
{id:91,name:"Korean (South)"},
{id:92,name:"Kyrgyz"},
{id:93,name:"Laotian"},
{id:94,name:"Latvian"},
{id:7,name:"Lebanese"},
{id:95,name:"Liberian"},
{id:8,name:"Libyan"},
{id:96,name:"Lithuanian"},
{id:97,name:"Luxembourger"},
{id:98,name:"Macedonian"},
{id:99,name:"Malagasy"},
{id:100,name:"Malawian"},
{id:101,name:"Malaysian"},
{id:102,name:"Maldivian"},
{id:103,name:"Malian"},
{id:104,name:"Maltese"},
{id:105,name:"Mauritanian"},
{id:106,name:"Mauritian"},
{id:107,name:"Mexican"},
{id:173,name:"Moldovan"},
{id:108,name:"Monegasque"},
{id:109,name:"Mongolian"},
{id:174,name:"Montenegrin"},
{id:9,name:"Moroccan"},
{id:35,name:"Motswana"},
{id:110,name:"Mozambican"},
{id:112,name:"Namibian"},
{id:113,name:"Nepali"},
{id:116,name:"New Zealander"},
{id:117,name:"Nicaraguan"},
{id:119,name:"Nigerian (Nigeria)"},
{id:118,name:"Nigerien (Niger)"},
{id:120,name:"Norwegian"},
{id:11,name:"Pakistani"},
{id:12,name:"Palestinian"},
{id:121,name:"Panamanian"},
{id:122,name:"Paraguayan"},
{id:123,name:"Peruvian"},
{id:125,name:"Polish"},
{id:126,name:"Portugese"},
{id:127,name:"Puerto Rican"},
{id:128,name:"Romanian"},
{id:129,name:"Russian"},
{id:130,name:"Rwandan"},
{id:163,name:"Sahrawi"},
{id:61,name:"Salvadoran"},
{id:131,name:"Sammarinese"},
{id:20,name:"Samoan"},
{id:132,name:"Senegalese"},
{id:165,name:"Serbian"},
{id:133,name:"Seychellois"},
{id:134,name:"Sierra Leonean"},
{id:135,name:"Singaporean"},
{id:136,name:"Slovak"},
{id:137,name:"Slovenes"},
{id:138,name:"Somali"},
{id:139,name:"South African"},
{id:140,name:"Spanish"},
{id:141,name:"Sri Lankan"},
{id:142,name:"Sudanese"},
{id:143,name:"Swazi"},
{id:144,name:"Swedish"},
{id:145,name:"Swiss"},
{id:15,name:"Syrian"},
{id:146,name:"Taiwanese"},
{id:147,name:"Tajik"},
{id:148,name:"Tanzanian"},
{id:149,name:"Thai"},
{id:59,name:"Timorese"},
{id:150,name:"Tongan"},
{id:151,name:"Trini"},
{id:16,name:"Tunisian"},
{id:152,name:"Turkish"},
{id:153,name:"Turkmen"},
{id:154,name:"Ugandan"},
{id:155,name:"Ukrainian"},
{id:158,name:"Uruguayan"},
{id:159,name:"Uzbek"},
{id:160,name:"Vatican Citizen"},
{id:161,name:"Venezuelan"},
{id:162,name:"Vietnames"},
{id:164,name:"Yemeni"},
{id:167,name:"Zambian"},
{id:168,name:"Zimbabwean"},
{id:1000,name:"Other"},
];

export const ngXLoaderType = "loader-01";
export const ngxUiLoaderConfig: NgxUiLoaderConfig  = {
    "bgsColor": "red",
    "bgsOpacity": 0.5,
    "bgsPosition": "bottom-left",
    "bgsSize": 60,
    "bgsType": "square-jelly-box",
    "blur": 9,
    "delay": 0,
    "fastFadeOut": true,
    "fgsColor": "#000971ad",
    "fgsPosition": "center-center",
    "fgsSize": 50,
    "fgsType": "wandering-cubes",
    "gap": 24,
    "logoPosition": "bottom-right",
    "logoSize": 90,
    "logoUrl": "",
    "masterLoaderId": "master",
    "overlayBorderRadius": "0",
    "overlayColor": "rgba(255,252,252,0.43)",
    "pbColor": "#ffffff",
    "pbDirection": "ltr",
    "pbThickness": 6,
    "hasProgressBar": true,
    "text": "",
    "textColor": "#FFFFFF",
    "textPosition": "center-center",
    "maxTime": -1,
    "minTime": 300
  };

  export const language = [
    {id:40,name:"Slovenian"},
    {id:42,name:"Swahili"},
    {id:44,name:"Tagalog"},
    {id:1,name:"Arabic"},
    {id:12,name:"English"},
    {id:4,name:"Afrikaans"},
    {id:16,name:"Farsi"},
    {id:21,name:"Hebrew"},
    {id:22,name:"Hindi"},
    {id:28,name:"Malay"},
    {id:29,name:"Malayalam"},
    {id:46,name:"Tamil"},
    {id:19,name:"Gujarati"},
    {id:51,name:"Urdu"},
    {id:27,name:"Konkani"},
    {id:30,name:"Marathi"},
    {id:49,name:"Telugu"},
    {id:2,name:"Albanian"},
    {id:3,name:"Armenian"},
    {id:5,name:"Bulgarian"},
    {id:6,name:"Cantonese"},
    {id:7,name:"Chinese"},
    {id:8,name:"Croatian"},
    {id:9,name:"Czech"},
    {id:10,name:"Danish"},
    {id:11,name:"Dutch"},
    {id:13,name:"Ethiopian"},
    {id:14,name:"Finnish"},
    {id:15,name:"French"},
    {id:17,name:"German"},
    {id:18,name:"Greek"},
    {id:20,name:"Hungarian"},
    {id:23,name:"Indonesian"},
    {id:24,name:"Italian"},
    {id:25,name:"Japanese"},
    {id:26,name:"Korean"},
    {id:31,name:"Mandarin"},
    {id:32,name:"Norwegian"},
    {id:33,name:"Polish"},
    {id:34,name:"Portuguese"},
    {id:35,name:"Romanian"},
    {id:36,name:"Russian"},
    {id:37,name:"Serbian"},
    {id:38,name:"Sinhala"},
    {id:39,name:"Slovakian"},
    {id:41,name:"Spanish"},
    {id:43,name:"Swedish"},
    {id:45,name:"Taiwanese"},
    {id:47,name:"Thai"},
    {id:48,name:"Turkish"},
    {id:50,name:"Ukrainian"},
    {id:52,name:"Vietnamese"},
  ];

  export const industry = [
    {id:55,name:"Accounting &amp; Auditing"},
    {id:2,name:"Advertising / PR / Event Management"},
    {id:3,name:"Agriculture / Dairy / Poultry / Livestock"},
    {id:52,name:"Air Conditioning / Refrigeration / HVAC"},
    {id:4,name:"Airlines / Aviation"},
    {id:5,name:"Architecture / Interior Designing"},
    {id:6,name:"Automotive / Automobile / Auto Accessories"},
    {id:7,name:"Banking / Financial Services / Broking"},
    {id:56,name:"Call Center / BPO / KPO / Outsourcing"},
    {id:57,name:"Ceramics / Sanitary ware"},
    {id:9,name:"Chemicals / Petrochemicals / Polymers / Industrial Gases"},
        {id:58,name:"Concrete / Readymix / Cement"},
    {id:10,name:"Construction / Civil Engineering"},
    {id:59,name:"Consulting / Management Consulting / Advisory Services"},
    {id:11,name:"Consumer Durables / Consumer Electronics"},
    {id:14,name:"Defence / Military / Government"},
    {id:15,name:"Education / Training / Teaching / Academics"},
    {id:60,name:"Elevators / Escalators"},
    {id:61,name:"Engineering Design &amp; Consulting"},
    {id:62,name:"Entertainment / Recreation / Theme Parks"},
    {id:63,name:"Facilities Management"},
    {id:17,name:"Fertilizers / Pesticides"},
    {id:64,name:"Fitness / Wellness / Gym / Salon / Spa"},
    {id:12,name:"FMCG / Foods / Beverages"},
    {id:18,name:"Fresher - No Industry Experience / Not Employed"},
    {id:65,name:"Furniture/Furnishings/Home Decor"},
    {id:16,name:"General Trading / Export / Import"},
    {id:66,name:"Glass"},
    {id:19,name:"Gold / Gems &amp; Jewellery"},
    {id:20,name:"Hotels / Hospitality"},
    {id:21,name:"Industrial Products / Heavy Machinery"},
    {id:22,name:"Insurance"},
    {id:23,name:"Internet / E-commerce / Dotcom"},
    {id:24,name:"IT - Hardware &amp; Networking"},
    {id:25,name:"IT - Software Services"},
    {id:67,name:"Landscaping"},
    {id:68,name:"Legal / Law Firm"},
    {id:13,name:"Logistics / Transportation / Warehousing / Courier"},
    {id:29,name:"Media / Publishing / TV / Radio / Outdoor / Digital"},
    {id: 30,name:"Medical / Healthcare / Diagnostics / Medical Devices"},
    {id:31,name:"Metals / Steel / Iron / Aluminium / Fabrication"},
        {id:69,name:"Metro / Railway / Train"},
    {id:54,name:"Mining / Forestry / Fishing"},
    {id:32,name:"NGO/Social Services/Community Services/Non-Profit"},
    {id:34,name:"Office Automation/Office Equipment/Office Supplies/Stationery"},
    {id:36,name:"Oil &amp; Gas / Petroleum"},
    {id:70,name:"Oil &amp; Gas: Consultancy, Design, FEED"},
        {id:71,name:"Oil &amp; Gas: Exploration, Drilling, Production, Field Services"},
    {id:72,name:"Oil &amp; Gas: Refining, Storage, Marketing, Distribution"},
    {id:1000,name:"Other"},
    {id:35,name:"Paper / Paper Pulp / Paper Mill"},
    {id:73,name:"Perfumery / Toiletries / Personal Care / Cosmetics"},
    {id:37,name:"Pharma / Biotech / Clinical Research"},
    {id:38,name:"Plastics / Rubber"},
    {id:39,name:"Power Generation / Power Distribution / Energy / Nuclear Energy"},
       {id:40,name:"Printing / Packaging"},
    {id:41,name:"Real Estate"},
    {id:42,name:"Recruitment / Placement Firm / Executive Search"},
    {id:53,name:"Restaurants / Catering / Food Services"},
    {id:43,name:"Retail"},
    {id:45,name:"Security / Law Enforcement"},
    {id:74,name:"Shipbuilding / Ship Repair / Ship Maintenance / Drydocks"},
        {id:46,name:"Shipping / Freight"},
    {id:47,name:"Telecom / ISP"},
    {id:75,name:"Testing / Inspection / Certification Services"},
    {id:49,name:"Textiles  Clothing / Apparels / Fashion / Accessories"},
    {id:76,name:"Travel / Tourism"},
    {id:50,name:"Tyres"},
    {id:77,name:"Water Treatment / De-Salination / Waste Management"},
  ]


  export enum IToastr {
      SUCCESS = "Success!!!",
      ERROR = "Error!!!",
      WARNING = "Warning!!!",
      INFO = "Info!!!",
  }


  export const config: AngularEditorConfig = {
    editable: true,
    spellcheck: true,
    width: '100%',
    minHeight: '5rem',
    maxHeight: "15rem",
    placeholder: 'Job Discription',
    translate: 'Yes',
    defaultParagraphSeparator: 'p',
    defaultFontName: 'Roboto, "Helvetica Neue", sans-serif',
    toolbarHiddenButtons: [
        [
          ],
          [
            'fontSize',
            'textColor',
            'backgroundColor',
            'customClasses',
            'link',
            'unlink',
            'insertImage',
            'insertVideo',
            'insertHorizontalRule',
            'removeFormat',
            'toggleEditorMode'
          ]
    ],
    customClasses: [
      {
        name: 'quote',
        class: 'quote'
      },
      {
        name: 'redText',
        class: 'redText'
      },
      {
        name: 'titleText',
        class: 'titleText',
        tag: 'h1'
      }
    ]
  };

  export const CURRENCY = [
      {
          symbol: "$",
          name: "US Dollar",
      },
      {
        symbol: "€",
        name: "Euro",
    },
      {
        symbol: "SAR",
        name: "Saudi Riyal",
    },
    {
        symbol: "AED",
        name: "UAE Dirham",
    },      {
        symbol: "BHD",
        name: "Bahraini Dinar",
    },      {
        symbol: "OMR",
        name: "Omani Rial",
    },      {
        symbol: "QR",
        name: "Qatari Riyal",
    },      {
        symbol: "₹",
        name: "Indian Rupees",
    },      {
        symbol: "£",
        name: "British Pound",
    },      {
        symbol: "KWD",
        name: "Kuwaiti Dinar",
    },
  ]